routes/web.php
<?php

use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\ProductController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::middleware(['auth' => 'admin'])->group(function() {

});

Route::prefix('admin')->group(function() {
    Route::get('/dashboard', [DashboardController::class, 'dashboard'])->name('dashboard');
});


Route::group(['prefix' => 'category', 'as' => 'category.'], function() {
    Route::get('/manage', [CategoryController::class, 'manage'])->name('manage');
    Route::get('/getdata', [CategoryController::class, 'getData'])->name('data');
    Route::get('/create', [CategoryController::class, 'create'])->name('create');
    Route::post('/create', [CategoryController::class, 'store'])->name('store');
    Route::get('/edit/{category}', [CategoryController::class, 'edit'])->name('edit');
    Route::put('/update/{category}', [CategoryController::class, 'update'])->name('update');
    Route::delete('/delete/{id}', [CategoryController::class, 'delete'])->name('delete');
});

Route::group(['prefix' => 'product', 'as' => 'product.'], function() {
    Route::get('/manage', [ProductController::class, 'manage'])->name('manage');
    Route::get('/getdata', [ProductController::class, 'getData'])->name('data');
    Route::get('/create', [ProductController::class, 'create'])->name('create');
    Route::post('/create', [ProductController::class, 'store'])->name('store');
    Route::get('/edit/{product}', [ProductController::class, 'edit'])->name('edit');
    Route::put('/update/{product}', [ProductController::class, 'update'])->name('update');
    Route::delete('/delete/{product}', [ProductController::class, 'delete'])->name('delete');
});

Route::group(['prefix' => 'orders', 'as' => 'order.'], function() {
    Route::get('/manage', [OrderController::class, 'manage'])->name('manage');
    Route::get('/getdata', [OrderController::class, 'getData'])->name('data');
    Route::get('/detail/{order}', [OrderController::class, 'orderDetail'])->name('detail');
    Route::get('/edit/{order}', [OrderController::class, 'shipped'])->name('edit');
    Route::put('/update/{order}', [OrderController::class, 'update'])->name('update');
    Route::get('/delete/{order}', [OrderController::class, 'delete'])->name('delete');
});

app/Models/Order.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Order extends Model
{
    use HasFactory;

    public function user()
    {
       return $this->belongsTo(User::class, 'user_id', 'id');
    }

    public function orderItems()
    {
        return $this->hasMany(OrderItems::class);
    }
}

app/Http/Controllers/Admin/OrderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Order;
use Illuminate\Http\Request;
use Yajra\DataTables\Facades\DataTables;

class OrderController extends Controller
{
    public function manage()
    {
        $data['table'] = [
            'table_url' => route('order.data'),
            'columns' => [
                [
                    'name' => 'user_name',
                    'label' => 'Pelanggan'
                ],
                [
                    'name' => 'order_date',
                    'label' => 'Tanggal Pesanan'
                ],
                [
                    'name' => 'total_amount',
                    'label' => 'Total Jumlah',
                ],
                [
                    'name' => 'status_order',
                    'label' => 'Status Pesanan',
                ],
                [
                    'name' => 'action',
                    'label' => 'Manage',
                ],
            ]
        ];
        return view('admin.orders.manage', $data);
    }

    public function getData()
    {
        try {
            $query = Order::select([
                'orders.id',
                'order_date',
                'total_amount',
                'status_order',
                'users.name as user_name'
            ])
            ->join('users', 'users.id', '=', 'orders.user_id')
            ->orderBy('order_date', 'desc');

            return DataTables::of($query)
            ->addColumn('action', function($order) {
                    $string = '<a href="'.route('order.edit', $order->id).'" class="btn btn-info btn-sm mr-3 " style="margin-right: 10px;"><i class="fas fa-edit"></i></a>';

                    $string .= '<button title="Hapus" class="btn btn-icon btn-sm btn-danger waves-effect waves-light delete-form"><i class="fa fa-trash"></i></button>';

                    $string .= '<form action="' . route('order.delete', $order->id) . '" method="POST">' . method_field('delete') . csrf_field() . '</form>';

                    return $string;
            })
            ->rawColumns(['action'])
            ->make(true);
        } catch (\Exception $error) {
            return $error->getMessage();
        }
    }

    public function orderDetail($id)
    {
        $detail['order'] = Order::findOrFail($id);
        try {
            if ($detail) {
                return view('admin.orders.detail', $detail);
            }
        } catch (\Exception $error) {
            return redirect()->back()->with('error', $error->getMessage());
        }
    }

    public function editStatus(Order $order)
    {
        $data['order'] = $order;
        return view('admin.orders.form', $data);
    }

    public function shipped(Request $request, Order $order)
    {
            $input['shipped'] = $request->input('shipped') ? true : false;
        try {
            $update =  $order->update($input);

            if ($update) {
                return redirect()->route('order.manage')->with('success', 'Berhasil mengubah status pesanan');
            }
            return redirect()->back()->with('error', 'Gagal mengubah status pesanan');
        } catch (\Exception $error) {
            return redirect()->back()->with('error', $error->getMessage());
        }
    }

    public function delete(String $id)
    {
        $delete = Order::findOrfail($id)->delete();
        try {
            if ($delete) {
                return redirect()->route('order.manage')->with('success', 'Berhasil menghapus data order');
            }
            return redirect()->back()->with('success', 'Gagal menghapus data order');

        } catch (\Exception $error) {
            return redirect()->back()->with('success', $error->getMessage());
        }
    }
}

resources/views/admin/orders/form.blade.php
@extends('layouts.master-admin')

@section('content')
<div class="row">
    <!-- Basic Layout -->
    <div class="col-xxl">
      <div class="card mb-4">
        <div class="card-header d-flex align-items-center justify-content-between">
          <h5 class="mb-0">Edit Order</h5>
          <small class="text-muted float-end">Default label</small>
        </div>
        <div class="card-body">
          <form action="post" method="{{ route('order.update', $order) }}" id="submitForm">
            @csrf
            @method('put')
            <div class="row mb-3">
              <label class="col-sm-2 col-form-label" for="basic-default-name">Status Pesanan</label>
              <div class="col-sm-10">
                <input class="form-check-input" name="shipped" type="checkbox" value="1" {{ $order->shipped == 1 ? 'checked': '' }}>
                <label class="form-check-label">Dikirim</label>
              </div>
            </div>
            <div class="row justify-content-end">
              <div class="col-sm-10">
                <button type="submit" submitForm="submit" class="btn btn-primary">Update</button>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
</div>
@endsection

resources/views/admin/orders/manage.blade.php
@extends('layouts.master-admin')

@section('content')
<div class="row">
    <div class="col-md-12">
        @include('layouts.message')
        <div class="card">
          <div class="card-header">
            <div class="card-title">
                <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                      <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                      <div class="input-group-append">
                        <button type="submit" class="btn btn-default">
                          <i class="fas fa-search"></i>
                        </button>
                      </div>
                    </div>
                </div>
            </div>
          </div>
          <!-- /.card-header -->
          <div class="card-body p-0">
            <table class="table table-striped" id="dataOrder">
              <thead>
                <tr>
                    @foreach($table['columns'] as $column)
                    <th>{{ $column['label'] }}</th>
                    @endforeach
                </tr>
              </thead>
              <tbody>
              </tbody>
            </table>
          </div>
        </div>
    </div>
</div>
@endsection
@push('script')
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<script src="/admin/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="/admin/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script type="text/javascript">
$(document).ready(function() {
    $('#dataOrder').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{{ $table['table_url'] }}',
        ordering: false,
        searching: false,
        paging: false,
        autoWidth: false,
        lengthChange: false,
        info: false,
        columns: [
            @foreach($table['columns'] as $column)
            {data: '{{ $column['name'] }}', name: '{{ $column['name'] }}'},
            @endforeach
        ],
    });
});
</script>
@endpush