routes/web.php
<?php

use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\ProductController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::middleware(['auth' => 'admin'])->group(function() {

});

Route::prefix('admin')->group(function() {
    Route::get('/dashboard', [DashboardController::class, 'dashboard'])->name('dashboard');
});


Route::group(['prefix' => 'category', 'as' => 'category.'], function() {
    Route::get('/manage', [CategoryController::class, 'manage'])->name('manage');
    Route::get('/getdata', [CategoryController::class, 'getData'])->name('data');
    Route::get('/create', [CategoryController::class, 'create'])->name('create');
    Route::post('/create', [CategoryController::class, 'store'])->name('store');
    Route::get('/edit/{category}', [CategoryController::class, 'edit'])->name('edit');
    Route::put('/update/{category}', [CategoryController::class, 'update'])->name('update');
    Route::delete('/delete/{id}', [CategoryController::class, 'delete'])->name('delete');
});

Route::group(['prefix' => 'product', 'as' => 'product.'], function() {
    Route::get('/manage', [ProductController::class, 'manage'])->name('manage');
    Route::get('/getdata', [ProductController::class, 'getData'])->name('data');
    Route::get('/create', [ProductController::class, 'create'])->name('create');
    Route::post('/create', [ProductController::class, 'store'])->name('store');
    Route::get('/edit/{product}', [ProductController::class, 'edit'])->name('edit');
    Route::put('/update/{product}', [ProductController::class, 'update'])->name('update');
    Route::delete('/delete/{product}', [ProductController::class, 'delete'])->name('delete');
});

Route::group(['prefix' => 'orders', 'as' => 'order.'], function() {
    Route::get('/manage', [OrderController::class, 'manage'])->name('manage');
    Route::get('/getdata', [OrderController::class, 'getData'])->name('data');
    Route::get('/detail/{order}', [OrderController::class, 'orderDetail'])->name('detail');
    Route::get('/edit/{order}', [OrderController::class, 'shipped'])->name('edit');
    Route::put('/update/{order}', [OrderController::class, 'update'])->name('update');
    Route::get('/delete/{order}', [OrderController::class, 'delete'])->name('delete');
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $fillable = ['category_id', 'name_product', 'image_product', 'description', 'price', 'quantity', 'slug'];

    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id', 'id');
    }
}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\ProductRequest;
use App\Models\Category;
use App\Models\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;
use Yajra\DataTables\Facades\DataTables;

class ProductController extends Controller
{
    public function manage()
    {
        $data['table'] = [
            'table_url' => route('product.data'),
            'create' => [
                'url' => route('product.create'),
                'label' => 'Tambah Product',
            ],
            'columns' => [
                [
                    'name' => 'name_product',
                    'label' => 'Produk',
                ],
                [
                    'name' => 'category_name',
                    'label' => 'Kategori'
                ],
                [
                    'name' => 'image_product',
                    'label' => 'Gambar',
                ],
                [
                    'name' => 'description',
                    'label' => 'Deskripsi',
                ],
                [
                    'name' => 'price',
                    'label' => 'Harga',
                ],
                [
                    'name' => 'quantity',
                    'label' => 'Kuantiti'
                ],
                [
                    'name' => 'action',
                    'label' => 'Manage'
                ]
            ]
        ];

        return view('admin.products.manage', $data);
    }

    public function getData()
    {
        try {
            $data = Product::select([
                'products.id',
                'products.name_product',
                'products.image_product',
                'products.description',
                'price',
                'quantity',
                'categories.name as category_name'
            ])
            ->join('categories', 'categories.id', '=', 'products.category_id')
            ->orderBy('name_product', 'asc');

            return DataTables::of($data)
                ->addColumn('price', function($product) {
                    return 'Rp. '. number_format($product->price, 0, ',', '.');
                })

                ->addColumn('action', function($product) {
                    $string = '<a href="'.route('product.edit', $product->id).'" class="btn btn-info btn-sm mr-3 " style="margin-right: 10px;"><i class="fas fa-edit"></i></a>';

                    $string .= '<button title="Hapus" class="btn btn-icon btn-sm btn-danger waves-effect waves-light delete-form"><i class="fa fa-trash"></i></button>';

                    $string .= '<form action="' . route('product.delete', $product->id) . '" method="POST">' . method_field('delete') . csrf_field() . '</form>';

                    return $string;
                })

                ->rawColumns(['action'])
                ->make(true);
        } catch (\Exception $error) {
            return $error->getMessage();
        }
    }

    public function create()
    {
        $category['categoryList'] = Category::query()->orderBy('name')->get();
        return view('admin.products.form', $category);
    }

    public function store(ProductRequest $request)
    {
        $input = $request->all();

        try {

            if ($request->hasFile('image_product')) {
                $imageFile = $request->image_product;
                $imageProduct = uniqid(). '_' . $imageFile->getClientOriginalExtension();
                $imageFile->move(public_path(). '/images/products/', $imageProduct);
            }

            $input['image_product'] = $imageProduct;
            $input['slug'] = Str::slug($request->input('name_product'));
            $create = Product::create($input);

            if ($create) {
                return redirect()->route('product.manage')->with('success', 'Berhasil menambahkan product');
            }
            return redirect()->back()->with('error', 'Gagal menambahkan data product');

        } catch (\Exception $error) {
            return redirect()->back()->with('error', $error->getMessage());
        }
    }

    public function edit(Product $product)
    {
        try {
            $data['product'] = $product;
            $data['categoryList'] = Category::query()->orderBy('name', 'asc')->get();
            return view('admin.products.form', $data);

        } catch (\Exception $error) {
            return redirect()->back()->with('error', $error->getMessage());
        }
    }

    public function update(Request $request, $id)
    {
        $product = Product::findOrFail($id);
        $pathImage = public_path(). '/images/products/'. $product->image_product;

        if ($request->hasFile('image_product')) {
            File::delete($pathImage);
            $imageFile = $request->image_product;
            $imageProduct = uniqid(). '_' . $imageFile->getClientOriginalExtension();
            $imageFile->move(public_path(). '/images/products/', $imageProduct);
        } elseif ($product->image_product) {
            $imageProduct = $product->image_product;
        } else {
            $imageProduct = null;
        }

        $inputUpdate = $request->all();
        $inputUpdate['slug'] = Str::slug($request->input('name_product'));

        try {
            $updateProduct = $product;

            $updateProduct->update($inputUpdate);

            if ($updateProduct->image_product) {
                $inputUpdate['image_product'] = $imageProduct;
            }

            $updateProduct->update($inputUpdate);

            if ($updateProduct) {
                return redirect()->route('product.manage')->with('succes', 'Berhasil mengubah data produk');
            }
            return redirect()->back()->with('error', 'Gagal mengubah data produk');

        } catch (\Exception $error) {
            return redirect()->back()->with('error', $error->getMessage());
        }
    }

    public function delete(String $id)
    {
        $delete = Product::findOrFail($id)->delete();
        try {
            if ($delete) {
                return redirect()->route('product.manage')->with('success', 'Berhasil menghapus data kategori');
            }
            return redirect()->back()->with('error', 'Gagal menghapus data kataegori');
        } catch (\Exception $error) {
            return redirect()->back()->with('error', $error->getMessage());
        }
    }
}

resources/views/admin/products/form.blade.php
@extends('layouts.master-admin')

@section('content')
@php
if (isset($product)) {
    $actionUrl = route('product.update', $product->id);
} else {
    $actionUrl = route('product.store');
}
@endphp
<div class="row">
    <div class="col-md-12">
    <div class="card card-seccond">
        <div class="card-header">
        <h3 class="card-title">Update Produk</h3>
        </div>
        <form id="submitProduct" method="POST" action="{{ $actionUrl }}" enctype="multipart/form-data">
            @if (@isset($product))
                {{ method_field('PUT') }}
                <input type="hidden" name="user_id" value="{{ $product->id }}" />
            @endif
            @csrf
            <div class="card-body">
                <div class="form-group">
                    <label>Kategori</label>
                    <select class="form-control" name="category_id" id="category_id" style="width: 100%;">
                        <option value="">Pilih kategori</option>
                    @foreach($categoryList as $category)
                    <option {{ isset($product) && $product->category_id == $category->id ? 'selected' : '' }} value="{{ $category->id }}">{{ $category->name }}</option>
                    @endforeach
                    </select>
                    @error('category')
                        <div class="mt-2 text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="name">Nama Produk</label>
                    <input type="text" class="form-control" name="name_product" id="name_product" placeholder="Nama Kategori" value="{{ isset($product) ? $product->name_product : old('name_product') }}">

                    @error('name_product')
                        <div class="mt-2 text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="image">Product Image</label>
                    @if (isset($product))
                        <div class="mb-3">
                            <img src="{{ asset('/images/products/'. $product->image_product) }}" alt="" style="width: 170px;" height="120px" class="img-rounded">
                        </div>
                    @endif
                    <div class="input-group">
                        <div class="custom-file">
                            <input type="file" class="custom-file-input" name="image_product" id="image_product">
                            <label class="custom-file-label" for="exampleInputFile">Choose file</label>
                        </div>
                        <div class="input-group-append">
                            <span class="input-group-text">Upload</span>
                        </div>
                    </div>

                    @error('image_product')
                        <div class="mt-2 text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="name">Deskripsi</label>
                    <textarea class="form-control" rows="3" name="description" id="description" placeholder="Deskripsi ...">{{ isset($product) ? $product->description : old('description') }}</textarea>

                    @error('description')
                        <div class="mt-2 text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="name">Price</label>
                    <input type="number" class="form-control" name="price" id="price" placeholder="Price" value="{{ isset($product) ? $product->price : old('price') }}">
                    @error('price')
                        <div class="mt-2 text-danger">{{ $message }}</div>
                    @enderror
                </div>
                <div class="form-group">
                    <label for="name">Quantity Item</label>
                    <input type="number" class="form-control" name="quantity" id="quantity" placeholder="Quantity Item" value="{{ isset($product) ? $product->quantity : old('quantity') }}">
                    @error('quantity')
                        <div class="mt-2 text-danger">{{ $message }}</div>
                    @enderror
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" submitProduct="submit" class="btn btn-info btn-sm">Submit</button>
            </div>
        </form>
    </div>
    </div>
</div>
@endsection

resources/views/admin/products/manage.blade.php
@extends('layouts.master-admin')

@section('content')
<div class="row">
    <div class="col-md-12">
        @include('layouts.message')
        <div class="card">
          <div class="card-header">
            <div class="card-title">
                <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                      <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                      <div class="input-group-append">
                        <button type="submit" class="btn btn-default">
                          <i class="fas fa-search"></i>
                        </button>
                      </div>
                    </div>
                </div>
            </div>

            <div class="card-tools">
                <span class="badge">
                    @if (@isset($table['create']))
                    <a href="{{ $table['create']['url'] }}" type="button" class="btn btn-info btn-sm">{{ $table['create']['label'] }}</a>
                    @endif
                </span>
            </div>
          </div>
          <!-- /.card-header -->
          <div class="card-body p-0">
            <table class="table table-striped" id="dataProduct">
              <thead>
                <tr>
                    @foreach($table['columns'] as $column)
                    <th>{{ $column['label'] }}</th>
                    @endforeach
                </tr>
              </thead>
              <tbody>
              </tbody>
            </table>
          </div>
        </div>
    </div>
</div>
@endsection
@push('script')
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<script src="/admin/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="/admin/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script type="text/javascript">
$(document).ready(function() {
    $('#dataProduct').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{{ $table['table_url'] }}',
        ordering: false,
        searching: false,
        paging: false,
        autoWidth: false,
        lengthChange: false,
        info: false,
        columns : [
            @foreach($table['columns'] as $column)
            { data: '{{ $column['name'] }}', name: '{{ $column['name'] }}'},
            @endforeach
        ],

        drawCallback: function(){
            // Delete Confirmation
            $(".delete-form").on("click", function(){
                var form = $(this).parent().find("form");
                Swal.fire({
                    title: 'Are you sure?',
                    text: "Apakah kamu yakin ingin menghapus kategori ini?",
                    type: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Yes!'
                }).then((result) => {
                    if (result.value) {
                        form.submit();
                    }
                })
            });
        }
    });
});
</script>
@endpush