routes/web.php
<?php

use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\OrderController;
use App\Http\Controllers\Admin\ProductController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


Route::middleware(['auth' => 'admin'])->group(function() {

});

Route::prefix('admin')->group(function() {
    Route::get('/dashboard', [DashboardController::class, 'dashboard'])->name('dashboard');
});


Route::group(['prefix' => 'category', 'as' => 'category.'], function() {
    Route::get('/manage', [CategoryController::class, 'manage'])->name('manage');
    Route::get('/getdata', [CategoryController::class, 'getData'])->name('data');
    Route::get('/create', [CategoryController::class, 'create'])->name('create');
    Route::post('/create', [CategoryController::class, 'store'])->name('store');
    Route::get('/edit/{category}', [CategoryController::class, 'edit'])->name('edit');
    Route::put('/update/{category}', [CategoryController::class, 'update'])->name('update');
    Route::delete('/delete/{id}', [CategoryController::class, 'delete'])->name('delete');
});

Route::group(['prefix' => 'product', 'as' => 'product.'], function() {
    Route::get('/manage', [ProductController::class, 'manage'])->name('manage');
    Route::get('/getdata', [ProductController::class, 'getData'])->name('data');
    Route::get('/create', [ProductController::class, 'create'])->name('create');
    Route::post('/create', [ProductController::class, 'store'])->name('store');
    Route::get('/edit/{product}', [ProductController::class, 'edit'])->name('edit');
    Route::put('/update/{product}', [ProductController::class, 'update'])->name('update');
    Route::delete('/delete/{product}', [ProductController::class, 'delete'])->name('delete');
});

Route::group(['prefix' => 'orders', 'as' => 'order.'], function() {
    Route::get('/manage', [OrderController::class, 'manage'])->name('manage');
    Route::get('/getdata', [OrderController::class, 'getData'])->name('data');
    Route::get('/detail/{order}', [OrderController::class, 'orderDetail'])->name('detail');
    Route::get('/edit/{order}', [OrderController::class, 'shipped'])->name('edit');
    Route::put('/update/{order}', [OrderController::class, 'update'])->name('update');
    Route::get('/delete/{order}', [OrderController::class, 'delete'])->name('delete');
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $table = 'categories';
    protected $fillable = ['name', 'slug', 'description'];

    public function products()
    {
        return $this->hasMany(Product::class);
    }
}

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\CategoryRequest;
use App\Models\Category;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Yajra\DataTables\Facades\DataTables;

class CategoryController extends Controller
{
    public function manage()
    {
        $data['table'] = [
            'table_url' => route("category.data"),
            'create' => [
                'url' => route('category.create'),
                'label' => 'Tambah Kategori'
            ],
            'columns' => [
                [
                    'name' => 'name',
                    'label' => 'Nama Kategori'
                ],
                [
                    'name' => 'description',
                    'label' => 'Deskripsi'
                ],
                [
                    'name' => 'created_at',
                    'label' => 'Tanggal Dibuat',
                ],
                [
                    'name' => 'action',
                    'label' => 'Manage',
                ],
            ]
        ];
        return view('admin.categories.manage', $data);
    }

    public function getData()
    {
        try {
            $query = Category::select([
                'categories.id',
                'name',
                'description',
                'created_at',
            ])->orderBy('name', 'asc');

            return DataTables::of($query)
            ->addColumn('created_at', function($item) {
                return date('d-m-Y H:is', strtotime($item->created_at));
            })
            ->addColumn('action', function($category) {
                $string = '<a href="'.route('category.edit', $category->id).'" class="btn btn-info btn-sm mr-3 " style="margin-right: 10px;"><i class="fas fa-edit"></i></a>';

                $string .= '<button title="Hapus" class="btn btn-icon btn-sm btn-danger waves-effect waves-light delete-form"><i class="fa fa-trash"></i></button>';

                $string .= '<form action="' . route('category.delete', $category->id) . '" method="POST">' . method_field('delete') . csrf_field() . '</form>';

                return $string;
            })
            ->rawColumns(['action'])
            ->make(true);

        } catch (\Exception $error) {
            return $error->getMessage();
        }
    }

    public function create()
    {
        return view('admin.categories.form');
    }

    public function store(CategoryRequest $request)
    {

        $input = $request->all();
        $input['slug'] = Str::slug($request->input('name'));

        try {
            $create = Category::create($input);
            if ($create) {
                return redirect()->route('category.manage')->with('success', 'Berhasil menambahkan kategoori');
            }

            return redirect()->back()->with('error', 'Gagal menambahkan kategori');

        } catch (\Exception $error) {
            return redirect()->back()->with('error', $error->getMessage());
        }
    }

    public function edit(Category $category)
    {
        try {
            $data['category'] = $category;
            return view('admin.categories.form', $data);
        } catch (\Exception $error) {
            return redirect()->back()->with('error', $error->getMessage());
        }
    }

    public function update(CategoryRequest $request, Category $category)
    {
        $inputUpdate = $request->all();
        $inputUpdate['slug'] = Str::slug($request->input('name'));

        try {
            $update = $category->update($inputUpdate);

            if ($update) {
                return redirect()->route('category.manage')->with('succes', 'Berhasil mengubah kategori');
            }
                return redirect()->back()->with('error', 'Gagal mengubah data kategori');
        } catch (\Exception $error) {
            return redirect()->back()->with('error', $error->getMessage());
        }
    }

    public function delete(String $id)
    {
        $category = Category::findOrFail($id)->delete();
        try {
            if ($category) {
                return redirect()->route('category.manage')->with('success', 'Berhasil menghapus kategori');
            }
            return redirect()->back()->with('error', 'Gagal menghapus kategori');
        } catch (\Exception $error) {
            return redirect()->back()->with('error', $error->getMessage());
        }

    }
}

resources/views/admin/categories/form.blade.php
@extends('layouts.master-admin')

@section('content')
@php
    if (isset($category)) {
        $actionUrl = route('category.update', $category->id);
    } else {
        $actionUrl = route('category.create');
    }
@endphp
<div class="row">
    <div class="col-md-12">
      <div class="card card-seccond">
        <div class="card-header">
          <h3 class="card-title">Edit Kategori</h3>
        </div>
        <form id="updateCategory" method="post" action="{{ $actionUrl }}" enctype="multipart/form-data">
            @if (@isset($category))
                {{ method_field('put') }}
                <input type="hidden" name="user_id" value="{{ $category->id }}" />
            @endif
        @csrf
          <div class="card-body">
            <div class="form-group">
              <label for="name">Nama Kategori</label>
              <input type="text" class="form-control" name="name" id="name" placeholder="Nama Kategori" value="{{ isset($category) ? $category->name : old('name') }}">
              @error('name')
                <div class="mt-2 text-danger">{{ $message }}</div>
              @enderror
            </div>
            <div class="form-group">
                <label for="name">Deskripsi</label>
                <textarea class="form-control" rows="3" name="description" id="description" placeholder="Deskripsi ...">{{ isset($category) ? $category->description : old('description') }}</textarea>
                @error('description')
                  <div class="mt-2 text-danger">{{ $message }}</div>
                @enderror
            </div>
          </div>
          <div class="card-footer">
            <button type="submit" class="btn btn-info btn-sm">Simpan</button>
          </div>
        </form>
      </div>
    </div>
</div>
@endsection
@push('script')
<script type="text/javascript">
$(document).ready(function() {
    $('#submitCategory').submit(function(e) {
        e.preventDefault();

        var form = $(this);
        var url = form.attr('action');
        var method = form.attr('method');
        var dataCategory = form.serialize();

        $.ajax({
            url: url,
            type: method,
            data: dataCategory,
            datType: 'json',
            success: function(response) {
                window.location = '/category/manage'
                console.log(response);
                // Display success message or perform any other actions
            },
            error: function(xhr) {
                console.log(xhr.responseText);
                // Handle error response
            }
        });
    });
});
</script>
@endpush

resources/views/admin/categories/manage.blade.php
@extends('layouts.master-admin')

@section('content')
<div class="row">
    <div class="col-md-12">
        @include('layouts.message')
        <div class="card">
          <div class="card-header">
            <div class="card-title">
                <div class="card-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                      <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

                      <div class="input-group-append">
                        <button type="submit" class="btn btn-default">
                          <i class="fas fa-search"></i>
                        </button>
                      </div>
                    </div>
                </div>
            </div>

            <div class="card-tools">
                <span class="badge">
                    @if (@isset($table['create']))
                    <a href="{{ $table['create']['url'] }}" type="button" class="btn btn-info btn-sm">{{ $table['create']['label'] }}</a>
                    @endif
                </span>
            </div>
          </div>
          <!-- /.card-header -->
          <div class="card-body p-0">
            <table class="table table-striped"  id="dataCategory">
                <thead>
                    <tr>
                        @foreach($table['columns'] as $column)
                        <th>{{ $column['label'] }}</th>
                        @endforeach
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
          </div>
        </div>
    </div>
</div>
@endsection
@push('script')
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<script src="/admin/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="/admin/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script type="text/javascript">
$(document).ready(function(){
    $('#dataCategory').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{{ $table['table_url'] }}',
        ordering: false,
        searching: false,
        paging: false,
        autoWidth: false,
        lengthChange: false,
        info: false,
        columns: [
                @foreach($table['columns'] as $column)
                { data: '{{ $column['name'] }}', name: '{{ $column['name'] }}' },
            @endforeach
        ],

        // Delete da from datatable
        drawCallback: function(){
            // Delete Confirmation
            $(".delete-form").on("click", function(){
                var form = $(this).parent().find("form");
                Swal.fire({
                    title: 'Are you sure?',
                    text: "Apakah kamu yakin ingin menghapus kategori ini?",
                    type: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Yes!'
                }).then((result) => {
                    if (result.value) {
                        form.submit();
                    }
                })
            });
        }
    });

    // $('.delete-form').on('submit', function(e) {
    //     e.preventDefault();

    //     $.ajax({
    //         type: 'post',
    //         headers: {
    //             'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
    //         },
    //         url: $(this).data('route'),
    //         data: {
    //         '_method': 'delete'
    //         },
    //         success: function (response, textStatus, xhr) {
    //         // alert('Data yang anda pilih akan dihapus')
    //         window.location='/category/manage'
    //         }
    //     });
    // })
});
</script>
@endpush